### PR TITLE
Adding Single Aminoacid Variant (SAV) splits

### PR DESCRIPTION
**Pull request by joaquimgomez**
Once applied, this PR will add Single Amino acid Variant (SAV) splits.

**Data explanation**:
Used simplified version of the data used in the paper "Embeddings from protein language models predict conservation and variant effects" by Marquet et al.
- `sequence.fasta`: FASTA file with the sequences of the proteins in the dataset
- `/labels/effect/*.effect`: Files with the SAVs of each protein. Encoded as, e.g., "X11Y 1" where X is the original AA, Y is the mutated AA, 11 is the position (1-indexed) and the last 1 means effect SAV and 0 means neutral SAV.
- `/labels/neutral/*.effect`: Same as `/labels/effect/*.effect`.

**Proposed splits**:
- `mixed`: train on wildtypes (with target `neutral`) and training folds 0-8, test on test fold 9
- `human`: same as mixed but only with human proteins
- `only_savs`: same as mixed but without wildtypes
- ~~`mixed`: cluster components (20% PIDE) and wild types for training and cluster representatives for testing~~
- ~~`human`: same as mixed, but using only human sequences~~

~~The clusterings have been carried out using MMseqs2 with `--min-seq-id 0.2`.~~

**To do**:
- [x] Change splits using provided folds
- [x] Add README
- [x] Add splits to FLIP/splits/README.md
- [ ] Add original data to the server (?)

**Issues**:
- [x] Publication to citate (dataset source)

### CODE REVIEW

**Comment by sacdallago** [comment]
#### Main
I don't quite get the data structure! I also don't see a `splits.zip` file so I'm confused where the splits are... but I'll try: So, this is a classification task with single amino acid substitutions. This is very similar to the original FLIP data except that it's a **binary** classification task instead of a regression task! The way I would expect the splits to look is a bunch of CSV files with the usual `sequence,target,set,..` columns, where, for each substitution a new sequence is generated, and the target is either `neutral` or `effect`. Let's assume:

- WT: `SEQVENCE`
- Has the follwoing annotations: `S1A=0;S1M=1;E2S=1`

This will result in a complete set of:
```
sequence,target,set
SEQVENCE,neutral,XX
AEQVENCE,neutral,XX
MEQVENCE,effect,XX
SSQVENCE,effect,XX
```

It seems that the `savs.csv` file is the closest file to this format I see. Mind that in this file, you don't need a mask, if you store the index of the residue substitution (e.g. 100, which you do) and the categorical class (e.g. effect, wt, neutral, which you could store). Also, the purpose of a "mask" as in the original FLIP datasets was to differentiate the type of modification (insertion, substitution, deletion,...); here there's always only one type of modification (substitution), and it will never be more than one (**single** amino acid variants ;) ). 

For your `only_savs` split, the above will simply be filtered down to:
```
sequence,target,set
AEQVENCE,neutral,XX
MEQVENCE,effect,XX
SSQVENCE,effect,XX
```
aka: remove the first sequence, which is the WT.

Importantly, in the end, all CSVs will always just contain two classes (again: it's a binary classification problem!).


#### Other points:
- **By visual inspection**: The sequences_dataframe.csv file has columns`id,sequence,neutral,effect`, but the neutral and effect columns seem to always be nan? I'd zip this file anyway, probably compresses well
- In the Notebook you do this counting of mutations, which I find is really cool. It'd probably be better displayed by sorting it descending by # of occurnances (what are the most common substitutions for effect vs non-effect vs both). In fact, and even more effective way to visualize this is by a 20x20 matrix: X and Y axis are the residues, the value is X subsituted by Y (just make sure you clarify which axis is which, aka X axis is original, Y axis is substitution). It goes in the direction of BLOSUM.
- Really interesting analysis also the # of proteins with # of mutations. Although the framing might need some tweaking: what's a protein with 1636 mutations? Are they all happening at the same time, or are there 1636 instances of the same protein with single mutations?
- Along the same lines: `residues_with_more_than_one_variation` how do I interpret this? `(0, 449): 1,` means that for sequence 0 at pos 449, there's an entry? Conversaly, what does `(123, 51): 2,` mean?
- I would not include `folds.zip` and `sequences_dataframe.csv` in the split folder: I don't see how these would help a user. Instead you probably want to modify `savs.csv` to look like the "mixed", which conversely is the same as the original publication, so I would just call it "from_publication" or something like that. The other two splits are basically just `SELECT` on this one.

**Comment by joaquimgomez** [comment]
> #### Main
> I don't quite get the data structure! I also don't see a `splits.zip` file so I'm confused where the splits are... but I'll try: So, this is a classification task with single amino acid substitutions. This is very similar to the original FLIP data except that it's a **binary** classification task instead of a regression task! The way I would expect the splits to look is a bunch of CSV files with the usual `sequence,target,set,..` columns, where, for each substitution a new sequence is generated, and the target is either `neutral` or `effect`. Let's assume:
> 
> * WT: `SEQVENCE`
> * Has the follwoing annotations: `S1A=0;S1M=1;E2S=1`
> 
> This will result in a complete set of:
> 
> ```
> sequence,target,set
> SEQVENCE,neutral,XX
> AEQVENCE,neutral,XX
> MEQVENCE,effect,XX
> SSQVENCE,effect,XX
> ```

-> This description is the one followed for the splits files, except for the target column. I forgot to zip the splits and then they were not uploaded. They are now uploaded in the new version.

> It seems that the `savs.csv` file is the closest file to this format I see. Mind that in this file, you don't need a mask, if you store the index of the residue substitution (e.g. 100, which you do) and the categorical class (e.g. effect, wt, neutral, which you could store). Also, the purpose of a "mask" as in the original FLIP datasets was to differentiate the type of modification (insertion, substitution, deletion,...); here there's always only one type of modification (substitution), and it will never be more than one (**single** amino acid variants ;) ).
> 
> For your `only_savs` split, the above will simply be filtered down to:
> 
> ```
> sequence,target,set
> AEQVENCE,neutral,XX
> MEQVENCE,effect,XX
> SSQVENCE,effect,XX
> ```
> 
> aka: remove the first sequence, which is the WT.

-> Format changed to follow this description, i.e., with the target with binary values effect/neutral.

> Importantly, in the end, all CSVs will always just contain two classes (again: it's a binary classification problem!).

-> WT have been considered `neutral`.

> #### Other points:
> * **By visual inspection**: The sequences_dataframe.csv file has columns`id,sequence,neutral,effect`, but the neutral and effect columns seem to always be nan? I'd zip this file anyway, probably compresses well

-> sequences_dataframe.csv has been deleted.

> * In the Notebook you do this counting of mutations, which I find is really cool. It'd probably be better displayed by sorting it descending by # of occurnances (what are the most common substitutions for effect vs non-effect vs both). In fact, and even more effective way to visualize this is by a 20x20 matrix: X and Y axis are the residues, the value is X subsituted by Y (just make sure you clarify which axis is which, aka X axis is original, Y axis is substitution). It goes in the direction of BLOSUM.

-> The visualization has been changed as suggested and improved.

> * Really interesting analysis also the # of proteins with # of mutations. Although the framing might need some tweaking: what's a protein with 1636 mutations? Are they all happening at the same time, or are there 1636 instances of the same protein with single mutations?

-> We have SAVs, so I understand that we have a protein that have 1636 instances in the dataset with 1636 distinct SAVs.

> * Along the same lines: `residues_with_more_than_one_variation` how do I interpret this? `(0, 449): 1,` means that for sequence 0 at pos 449, there's an entry? Conversaly, what does `(123, 51): 2,` mean?

-> “(0, 449): 1” means that for the protein with index 0 in the dataframe, the residue 449 has 1 variation. I have changed the visualization to show only the residues with more than one variation.

> * I would not include `folds.zip` and `sequences_dataframe.csv` in the split folder: I don't see how these would help a user. Instead you probably want to modify `savs.csv` to look like the "mixed", which conversely is the same as the original publication, so I would just call it "from_publication" or something like that. The other two splits are basically just `SELECT` on this one.

-> folds.zip and sequences_dataframe.csv  have been deleted.

**Comment by joaquimgomez** [comment]
Originally the source paper was the one by Marquet et al. about SAVs, but if I correctly understood, the final data comes from SNAP2 dataset, then, what paper should be cited?

**Comment by sacdallago** [comment]
> 
Originally the source paper was the one by Marquet et al. about SAVs, but if I correctly understood, the final data comes from SNAP2 dataset, then, what paper should be cited?

Both :)

**Comment by sacdallago** [comment]
Looks good. Once the READMEs have been adjusted, it's good to go

**Comment by joaquimgomez** [comment]
Publications added. Ready to merge!

**Pull request merged**
